version: '3.4'

services:
  database_redis:
    image: redis:latest
    ports:
      - 9379:6379

  api:
    build: .
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - 9000:9000
    depends_on:
      - database
