let hedgehogsFromEnv: string;

try {
  hedgehogsFromEnv = JSON.parse(process.env.HEDGEHOGS);
} catch (error) {
  hedgehogsFromEnv = '';
}

export const hedgehogs = (hedgehogsFromEnv as any) || [
  {
    where: 'Brest',
    who: 'Natasha and Tanja',
    when: '2013.05.XX',
    url: 'https://zinovikbot.herokuapp.com/1.jpg',
  },
  {
    where: 'Львiв',
    who: 'Max',
    when: '2013.07.29',
    url: 'https://zinovikbot.herokuapp.com/2.jpg',
  },
  {
    where: 'Крым',
    who: 'Roma and Lena',
    when: '2013.08.XX',
    url: 'https://zinovikbot.herokuapp.com/3.jpg',
  },
  {
    where: 'Нясвiж',
    who: 'Roma and Lena',
    when: '2013.10.XX',
    url: 'https://zinovikbot.herokuapp.com/4.jpg',
  },
  {
    where: 'Brest',
    who: 'Roma and Lena',
    when: '2014.01.XX',
    url: 'https://zinovikbot.herokuapp.com/5.jpg',
  },
  {
    where: 'Мiр',
    who: 'Lena',
    when: '2014.04.12',
    url: 'https://zinovikbot.herokuapp.com/6.jpg',
  },
  {
    where: 'Нясвiж & Мiр 1',
    who: 'Lena',
    when: '2014.04.12',
    url: 'https://zinovikbot.herokuapp.com/7.jpg',
  },
  {
    where: 'Нясвiж & Мiр 2',
    who: 'Lena',
    when: '2014.04.12',
    url: 'https://zinovikbot.herokuapp.com/8.jpg',
  },
  {
    where: 'Гародня',
    who: 'Lena',
    when: '2014.04.22',
    url: 'https://zinovikbot.herokuapp.com/9.jpg',
  },
  {
    where: 'Полацк',
    who: 'Lena',
    when: '2014.04.24',
    url: 'https://zinovikbot.herokuapp.com/10.jpg',
  },
  {
    where: 'Mensk',
    who: 'Lena',
    when: '2014.04.25',
    url: 'https://zinovikbot.herokuapp.com/11.jpg',
  },
  {
    where: 'Brest',
    who: 'Lena',
    when: '2014.06.XX',
    url: 'https://zinovikbot.herokuapp.com/12.jpg',
  },
  {
    where: 'Brest',
    who: 'Max',
    when: '2014.06.XX',
    url: 'https://zinovikbot.herokuapp.com/13.jpg',
  },
  {
    where: 'Рэчыца',
    who: 'Max',
    when: '2014.08.18',
    url: 'https://zinovikbot.herokuapp.com/14.jpg',
  },
  {
    where: 'Brest',
    who: 'Lena',
    when: '2014.08.ХХ',
    url: 'https://zinovikbot.herokuapp.com/15.jpg',
  },
  {
    where: 'Гародня',
    who: 'Lena',
    when: '2014.09.0X',
    url: 'https://zinovikbot.herokuapp.com/16.jpg',
  },
  {
    where: 'Moscow',
    who: 'Vitalik',
    when: '2015.01.02',
    url: 'https://zinovikbot.herokuapp.com/17.jpg',
  },
  {
    where: 'Biala Podlaska',
    who: 'Max',
    when: '2015.01.31',
    url: 'https://zinovikbot.herokuapp.com/18.jpg',
  },
  {
    where: 'Brest',
    who: 'Max',
    when: '2015.02.14',
    url: 'https://zinovikbot.herokuapp.com/19.jpg',
  },
  {
    where: 'Brest',
    who: 'Max',
    when: '2015.03.08',
    url: 'https://zinovikbot.herokuapp.com/20.jpg',
  },
  {
    where: 'Terespol',
    who: 'Max',
    when: '2015.03.30',
    url: 'https://zinovikbot.herokuapp.com/21.jpg',
  },
  {
    where: 'Moscow',
    who: 'Lena',
    when: '2015.04.24',
    url: 'https://zinovikbot.herokuapp.com/22.jpg',
  },
  {
    where: 'Oberhof',
    who: 'Ирка',
    when: '2015.04.28',
    url: 'https://zinovikbot.herokuapp.com/23.jpg',
  },
  {
    where: 'Brest',
    who: 'Христина',
    when: '2015.05.23',
    url: 'https://zinovikbot.herokuapp.com/24.jpg',
  },
  {
    where: 'Brest',
    who: 'Max',
    when: '2015.05.24',
    url: 'https://zinovikbot.herokuapp.com/25.jpg',
  },
  {
    where: 'Krakow',
    who: 'Lena',
    when: '2015.06.14',
    url: 'https://zinovikbot.herokuapp.com/26.jpg',
  },
  {
    where: 'Дудуткi',
    who: 'Lena',
    when: '2015.06.20',
    url: 'https://zinovikbot.herokuapp.com/27.jpg',
  },
  {
    where: 'Vilnius',
    who: 'Lena',
    when: '2015.08.15',
    url: 'https://zinovikbot.herokuapp.com/28.jpg',
  },
  {
    where: 'Trakai',
    who: 'Lena',
    when: '2015.08.16',
    url: 'https://zinovikbot.herokuapp.com/29.jpg',
  },
  {
    where: 'Санкт-Петербург',
    who: 'Roma and Lena',
    when: '2015.08.29',
    url: 'https://zinovikbot.herokuapp.com/30.jpg',
  },
  {
    where: 'Praha 1',
    who: 'Lena',
    when: '2015.12.31',
    url: 'https://zinovikbot.herokuapp.com/31.jpg',
  },
  {
    where: 'Praha 2',
    who: 'Lena',
    when: '2015.12.31',
    url: 'https://zinovikbot.herokuapp.com/32.jpg',
  },
  {
    where: 'Warszawa',
    who: 'Lena',
    when: '2016.02.13',
    url: 'https://zinovikbot.herokuapp.com/33.jpg',
  },
  {
    where: 'Gdansk',
    who: 'Lena',
    when: '2016.02.14',
    url: 'https://zinovikbot.herokuapp.com/34.jpg',
  },
  {
    where: 'Gdynia',
    who: 'Lena',
    when: '2016.02.14',
    url: 'https://zinovikbot.herokuapp.com/35.jpg',
  },
  {
    where: 'Brest',
    who: 'Kirill',
    when: '2016.02.19',
    url: 'https://zinovikbot.herokuapp.com/36.jpg',
  },
  {
    where: 'Kamarova',
    who: 'Lena',
    when: '2016.06.25',
    url: 'https://zinovikbot.herokuapp.com/37.jpg',
  },
  {
    where: 'Kyiv',
    who: 'Lena',
    when: '2016.07.10',
    url: 'https://zinovikbot.herokuapp.com/38.jpg',
  },
  {
    where: 'Canada',
    who: 'Andrey',
    when: '2016.07.12',
    url: 'https://zinovikbot.herokuapp.com/39.jpg',
  },
  {
    where: 'Odesa',
    who: 'Max',
    when: '2016.07.17',
    url: 'https://zinovikbot.herokuapp.com/40.jpg',
  },
  {
    where: 'Brest',
    who: 'Max',
    when: '2016.10.29',
    url: 'https://zinovikbot.herokuapp.com/41.jpg',
  },
  {
    where: 'Munchen',
    who: 'Сашка',
    when: '2016.12.27',
    url: 'https://zinovikbot.herokuapp.com/42.jpg',
  },
  {
    where: 'Uzhgorod',
    who: 'Lena',
    when: '2017.01.01',
    url: 'https://zinovikbot.herokuapp.com/43.jpg',
  },
  {
    where: 'Львiв',
    who: 'Lena',
    when: '2017.01.02',
    url: 'https://zinovikbot.herokuapp.com/44.jpg',
  },
  {
    where: 'Watsonville',
    who: 'Sandra',
    when: '2017.01.11',
    url: 'https://zinovikbot.herokuapp.com/45.jpg',
  },
  {
    where: 'Brest',
    who: 'Natashka',
    when: '2017.01.20',
    url: 'https://zinovikbot.herokuapp.com/46.jpg',
  },
  {
    where: 'Bukovel',
    who: 'Lena',
    when: '2017.02.16',
    url: 'https://zinovikbot.herokuapp.com/47.jpg',
  },
  {
    where: 'Saint Petersburg',
    who: 'Lena',
    when: '2017.06.26',
    url: 'https://zinovikbot.herokuapp.com/48.jpg',
  },
  {
    where: 'Aarhus',
    who: 'Irka',
    when: '2017.09.30',
    url: 'https://zinovikbot.herokuapp.com/49.jpg',
  },
  {
    where: 'Brest',
    who: 'Santa Claus',
    when: '2018.01.01',
    url: 'https://zinovikbot.herokuapp.com/50.jpg',
  },
  {
    where: 'Vilnius',
    who: 'Vitalik',
    when: '2018.01.27',
    url: 'https://zinovikbot.herokuapp.com/51.jpg',
  },
  {
    where: 'Bukovel',
    who: 'Lena',
    when: '2018.01.31',
    url: 'https://zinovikbot.herokuapp.com/52.jpg',
  },
  {
    where: 'Trier',
    who: 'Natasha',
    when: '2018.05.05',
    url: 'https://zinovikbot.herokuapp.com/53.jpg',
  },
  {
    where: 'Pinsk',
    who: 'Lena',
    when: '2018.08.12',
    url: 'https://zinovikbot.herokuapp.com/54.jpg',
  },
  {
    where: 'Warsaw',
    who: 'Sergey and Masha',
    when: '2018.09.20',
    url: 'https://zinovikbot.herokuapp.com/55.jpg',
  },
  {
    where: 'Harelbeke',
    who: 'Artur',
    when: '2018.10.16',
    url: 'https://zinovikbot.herokuapp.com/56.jpg',
  },
  {
    where: 'Riga',
    who: 'Lena',
    when: '2018.11.17',
    url: 'https://zinovikbot.herokuapp.com/57.jpg',
  },
  {
    where: 'Vienna',
    who: 'Lena',
    when: '2018.12.31',
    url: 'https://zinovikbot.herokuapp.com/58.jpg',
  },
  {
    where: 'Budapest',
    who: 'Lena',
    when: '2019.01.01',
    url: 'https://zinovikbot.herokuapp.com/59.jpg',
  },
];
